# github.com/go-task/task

push:
  cmds:
    - echo "Publish all changes to origin branch."
    - git push
    - git push --tags
  silent: true

npm-publish:
  cmds:
    - echo "Publish new version on npm."
    - npm publish ./

publish:
  deps: [npm-publish, push]
  desc: Publish development changes.

compile:
  cmds:
    - echo "Compiling js version..."
    - tsc -p ./ --outDir dist/
  silent: true

test:
  cmds:
    - npm test
  silent: true
  desc: Run mocha tests.

debug:
  cmds:
    - npm run-script debug
  silent: true
  desc: Debug mocha tests.